# Generated by Django 4.2.13 on 2024-06-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50)),
                ('current_academic_year', models.CharField(max_length=20)),
                ('dean_name', models.CharField(max_length=255)),
                ('chief_secretary_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
