// Auth Dispatch States
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';

// Profile Dispatch States
export const LOAD_USER_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS';
export const LOAD_USER_PROFILE_FAIL = 'LOAD_USER_PROFILE_FAIL';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';

// Update Students Dispatch States
export const UPDATE_STUDENTS_SUCCESS = 'UPDATE_STUDENTS_SUCCESS';
export const UPDATE_STUDENTS_FAILURE = 'UPDATE_STUDENTS_FAIL';

export const UPDATE_STUDENTS_REQUEST = 'UPDATE_STUDENTS_REQUEST';
export const UPDATE_STUDENTS_FILE_ERROR = 'UPDATE_STUDENTS_FILE_ERROR';

// Create Student Dispatch States
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_FAILURE = 'CREATE_STUDENT_FAIL';

export const CREATE_STUDENT_REQUEST = 'CREATE_STUDENT_REQUEST';


// Fetch Student Dispatch States
export const FETCH_STUDENT_REQUEST = 'FETCH_STUDENT_REQUEST';
export const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS';
export const FETCH_STUDENT_FAILURE = 'FETCH_STUDENT_FAILURE';

// Update Student Dispatch States
export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAILURE = 'UPDATE_STUDENT_FAILURE';

// Fetch Students Dispatch States
export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';

// Update Secretaries Dispatch States
export const UPDATE_SECRETARIES_REQUEST = 'UPDATE_SECRETARIES_REQUEST';
export const UPDATE_SECRETARIES_SUCCESS = 'UPDATE_SECRETARIES_SUCCESS';
export const UPDATE_SECRETARIES_FAILURE = 'UPDATE_SECRETARIES_FAILURE';
export const UPDATE_SECRETARIES_FILE_ERROR = 'UPDATE_SECRETARIES_FILE_ERROR';

// Fetch Secretaries Dispatch States
export const FETCH_SECRETARIES_REQUEST = 'FETCH_SECRETARIES_REQUEST';
export const FETCH_SECRETARIES_SUCCESS = 'FETCH_SECRETARIES_SUCCESS';
export const FETCH_SECRETARIES_FAILURE = 'FETCH_SECRETARIES_FAILURE';

// Fetch Secretary Dispatch States
export const FETCH_SECRETARY_REQUEST = 'FETCH_SECRETARY_REQUEST';
export const FETCH_SECRETARY_SUCCESS = 'FETCH_SECRETARY_SUCCESS';
export const FETCH_SECRETARY_FAILURE = 'FETCH_SECRETARY_FAILURE';

// Update Secretary Dispatch States
export const UPDATE_SECRETARY_REQUEST = 'UPDATE_SECRETARY_REQUEST';
export const UPDATE_SECRETARY_SUCCESS = 'UPDATE_SECRETARY_SUCCESS';
export const UPDATE_SECRETARY_FAILURE = 'UPDATE_SECRETARY_FAILURE';

// Update Faculties Dispatch States
export const UPDATE_FACULTIES_SUCCESS = 'UPDATE_FACULTIES_SUCCESS';
export const UPDATE_FACULTIES_FAILURE = 'UPDATE_FACULTIES_FAIL';

export const UPDATE_FACULTIES_REQUEST = 'UPDATE_FACULTIES_REQUEST';
export const UPDATE_FACULTIES_FILE_ERROR = 'UPDATE_FACULTIES_FILE_ERROR';

// Fetch Faculties Dispatch States
export const FETCH_FACULTIES_REQUEST = 'FETCH_FACULTIES_REQUEST';
export const FETCH_FACULTIES_SUCCESS = 'FETCH_FACULTIES_SUCCESS';
export const FETCH_FACULTIES_FAILURE = 'FETCH_FACULTIES_FAILURE';

// Fetch Certificates Dispatch States
export const FETCH_CERTIFICATES_FAILURE = 'FETCH_CERTIFICATES_FAILURE';
export const FETCH_CERTIFICATES_REQUEST = 'FETCH_CERTIFICATES_REQUEST';
export const FETCH_CERTIFICATES_SUCCESS = 'FETCH_CERTIFICATES_SUCCESS';

export const FETCH_CERTIFICATES_PRINT_FAILURE = 'FETCH_CERTIFICATES_PRINT_FAILURE';
export const FETCH_CERTIFICATES_PRINT_REQUEST = 'FETCH_CERTIFICATES_PRINT_REQUEST';
export const FETCH_CERTIFICATES_PRINT_SUCCESS = 'FETCH_CERTIFICATES_PRINT_SUCCESS';

export const FETCH_REJECTED_CERTIFICATES_FAILURE = 'FETCH_REJECTED_CERTIFICATES_FAILURE';
export const FETCH_REJECTED_CERTIFICATES_REQUEST = 'FETCH_REJECTED_CERTIFICATES_REQUEST';
export const FETCH_REJECTED_CERTIFICATES_SUCCESS = 'FETCH_REJECTED_CERTIFICATES_SUCCESS';

export const FETCH_APPROVED_CERTIFICATES_FAILURE = 'FETCH_APPROVED_CERTIFICATES_FAILURE';
export const FETCH_APPROVED_CERTIFICATES_REQUEST = 'FETCH_APPROVED_CERTIFICATES_REQUEST';
export const FETCH_APPROVED_CERTIFICATES_SUCCESS = 'FETCH_APPROVED_CERTIFICATES_SUCCESS';

export const FETCH_CERTIFICATE_FAILURE = 'FETCH_CERTIFICATE_FAILURE';
export const FETCH_CERTIFICATE_REQUEST = 'FETCH_CERTIFICATE_REQUEST';
export const FETCH_CERTIFICATE_SUCCESS = 'FETCH_CERTIFICATE_SUCCESS';

export const APPROVE_CERTIFICATE_FAILURE = 'APPROVE_CERTIFICATE_FAILURE';
export const APPROVE_CERTIFICATE_REQUEST = 'APPROVE_CERTIFICATE_REQUEST';
export const APPROVE_CERTIFICATE_SUCCESS = 'APPROVE_CERTIFICATE_SUCCESS';

export const REJECT_CERTIFICATE_FAILURE = 'REJECT_CERTIFICATE_FAILURE';
export const REJECT_CERTIFICATE_REQUEST = 'REJECT_CERTIFICATE_REQUEST';
export const REJECT_CERTIFICATE_SUCCESS = 'REJECT_CERTIFICATE_SUCCESS';

export const EDIT_CERTIFICATE_FAILURE = 'EDIT_CERTIFICATE_FAILURE';
export const EDIT_CERTIFICATE_REQUEST = 'EDIT_CERTIFICATE_REQUEST';
export const EDIT_CERTIFICATE_SUCCESS = 'EDIT_CERTIFICATE_SUCCESS';

export const SET_CERTIFICATES_PRINTED_REQUEST = 'SET_CERTIFICATES_PRINTED_REQUEST';
export const SET_CERTIFICATES_PRINTED_FAILURE = 'SET_CERTIFICATES_PRINTED_FAILURE';
export const SET_CERTIFICATES_PRINTED_SUCCESS = 'SET_CERTIFICATES_PRINTED_SUCCESS';

export const DOWNLOAD_CERTIFICATES_REQUEST = 'DOWNLOAD_CERTIFICATES_REQUEST';
export const DOWNLOAD_CERTIFICATES_FAILURE = 'DOWNLOAD_CERTIFICATES_FAILURE';
export const DOWNLOAD_CERTIFICATES_SUCCESS = 'DOWNLOAD_CERTIFICATES_SUCCESS';

export const FETCH_FACULTY_REQUEST = 'FETCH_FACULTY_REQUEST';
export const FETCH_FACULTY_FAILURE = 'FETCH_FACULTY_FAILURE';
export const FETCH_FACULTY_SUCCESS = 'FETCH_FACULTY_SUCCESS';
export const UPDATE_FACULTY_REQUEST = 'UPDATE_FACULTY_REQUEST';
export const UPDATE_FACULTY_SUCCESS = 'UPDATE_FACULTY_SUCCESS';
export const UPDATE_FACULTY_FAILURE = 'UPDATE_FACULTY_FAILURE';

export const ADD_SECRETARY_REQUEST = 'ADD_SECRETARY_REQUEST';
export const ADD_SECRETARY_SUCCESS = 'ADD_SECRETARY_SUCCESS';
export const ADD_SECRETARY_FAILURE = 'ADD_SECRETARY_FAILURE';

export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE';

export const RESET_APPLICATION_REQUEST = 'RESET_APPLICATION_REQUEST';
export const RESET_APPLICATION_SUCCESS = 'RESET_APPLICATION_SUCCESS';
export const RESET_APPLICATION_FAILURE = 'RESET_APPLICATION_FAILURE';

export const DOWNLOAD_ALL_CERTIFICATES_FAILURE = 'DOWNLOAD_ALL_CERTIFICATES_FAILURE';
export const DOWNLOAD_ALL_CERTIFICATES_REQUEST = 'DOWNLOAD_ALL_CERTIFICATES_REQUEST';
export const DOWNLOAD_ALL_CERTIFICATES_SUCCESS = 'DOWNLOAD_ALL_CERTIFICATES_SUCCESS';



