# Generated by Django 4.2.13 on 2024-06-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secretary_profile', '0001_initial'),
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100)),
                ('registration_date', models.DateField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('rejection_motive', models.TextField(null=True)),
                ('processing_date', models.DateField()),
                ('processing_position', models.IntegerField()),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretary_profile.secretaryprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.studentprofile')),
            ],
        ),
    ]
