# Generated by Django 4.2.13 on 2024-06-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('study_program_name', models.CharField(max_length=100)),
                ('study_cycle', models.CharField(max_length=100)),
                ('study_year', models.PositiveSmallIntegerField()),
                ('study_domain', models.CharField(max_length=100)),
                ('study_form', models.CharField(default='IF', max_length=2)),
                ('funding', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
    ]
